language: python
python: 2.7
install:
    - pip install tox
    - pip install coveralls
    - pip install -r requirements.txt
script: coverage run --source=pybal setup.py test
after_success: coveralls
